name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 2.1.1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.6'

dependencies:
  # Plugin for parsing html
#  html: '>=0.15.0 <1.0.0'
  html: ^0.15.4

  # Plugins for parsing css
#  csslib: '>=0.17.0 <1.0.0'
  csslib: ^1.0.0

  # Plugins for rendering the <table> tag.
#  flutter_layout_grid: '>=1.0.1 <2.0.0'
  flutter_layout_grid: ^2.0.3

  # Plugins for rendering the <video> tag.
#  video_player: '>=2.1.1 <3.0.0'
#  chewie: '>=1.0.0 <2.0.0'

  video_player: ^2.6.1
  chewie: 
    git:
      url:https://github.com/sasen98/chewie

  # Plugin for rendering the <iframe> tag.
#  webview_flutter: '>=2.0.4 <3.0.0'
  webview_flutter: ^4.2.2


  # Plugins for rendering the <audio> tag.
#  chewie_audio: '>=1.2.0 <2.0.0'
  chewie_audio: ^1.5.0

  # Plugins for rendering the <svg> tag.
#  flutter_svg: '>=0.22.0 <1.0.0'
  flutter_svg: ^2.0.6

  # Plugin for rendering MathML
#  flutter_math_fork: '>=0.3.3+1 <1.0.0'
  flutter_math_fork: ^0.7.1

  # plugin for firstWhereOrNull extension on lists
#  collection: '>=1.15.0 <2.0.0'
  collection: ^1.17.1

  # plugin to convert integers to numerals
#  numerus: '>=1.1.1 <2.0.0'
  numerus: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
